default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: password
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rentable_development

test:
  <<: *default
  database: rentable_test

sit:
  <<: *default
  database: rentable_sit
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV["RENTABLE_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

uat:
  <<: *default
  database: rentable_uat
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV["RENTABLE_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    database: rentable_production
    username: <%= ENV.fetch("DB_USER", "rentable") %>
    password: <%= ENV["RENTABLE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rentable_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rentable_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rentable_production_cable
    migrations_paths: db/cable_migrate
